// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2mKpYE1Cd82uxX082nFa2XrxzQBtJkgc',
    appId: '1:598635141763:web:a25ab36be863910d8159b6',
    messagingSenderId: '598635141763',
    projectId: 'jarvis-908bb',
    authDomain: 'jarvis-908bb.firebaseapp.com',
    storageBucket: 'jarvis-908bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdE-sIQ-ySGF92o8bMl3jNh56Ev-7UxY',
    appId: '1:598635141763:android:95f619461c700e5a8159b6',
    messagingSenderId: '598635141763',
    projectId: 'jarvis-908bb',
    storageBucket: 'jarvis-908bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vzyZIr-xwLYCnk8n5yvH90VkKGzbfMo',
    appId: '1:598635141763:ios:d48e44ccc1be39d78159b6',
    messagingSenderId: '598635141763',
    projectId: 'jarvis-908bb',
    storageBucket: 'jarvis-908bb.appspot.com',
    iosClientId: '598635141763-cj11rn9scknhfd4m0tgul5vuu81mq1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.reproductorIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vzyZIr-xwLYCnk8n5yvH90VkKGzbfMo',
    appId: '1:598635141763:ios:d48e44ccc1be39d78159b6',
    messagingSenderId: '598635141763',
    projectId: 'jarvis-908bb',
    storageBucket: 'jarvis-908bb.appspot.com',
    iosClientId: '598635141763-cj11rn9scknhfd4m0tgul5vuu81mq1ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.reproductorIa',
  );
}
